#!/usr/bin/env node
// Generator for the import-heavy benchmark fixture. Emits, deterministically:
//   mods/mNN.mts          — 60 ESM modules, 8 exported functions each (480 total)
//   mods/index.mts        — a barrel re-exporting all of them
//   heavy-snapshot-entry.cjs — a CommonJS V8-snapshot build entry that INLINES
//                              the SAME 480 functions (TS types stripped) plus
//                              the same reduce driver, since mksnapshot can't
//                              evaluate an ESM graph at build time.
//
// The point is a real parse/compile/instantiate cost with trivial per-call
// compute, so the heavy group stays startup-dominated. heavy.mts (the ESM entry)
// is hand-written and not regenerated here.
//
//   node heavy/gen-mods.mjs        # run from examples/cook
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const N = 60; // modules
const F = 8; // functions per module
const K = 6; // mix steps per function

mkdirSync(join(here, "mods"), { recursive: true });

// Body of one function mI_fF, as a string. `decl` picks `export function` (for
// the .mts modules) vs a plain `function` + FNS.push (for the snapshot entry).
function fnSource(i, f, { decl, types }) {
  const x = types ? "x: number): number" : "x)";
  let s = `${decl} m${i}_f${f}(${x} {\n  let acc = x + ${i} * ${f};\n`;
  for (let k = 0; k < K; k++) s += `  acc = (acc * ${k + 2} + ${i + f + k}) % 1000003;\n`;
  s += `  return acc;\n}\n`;
  return s;
}

// 1) the ESM modules + barrel
for (let i = 0; i < N; i++) {
  let body = `// module ${i}\n`;
  for (let f = 0; f < F; f++) body += fnSource(i, f, { decl: "export function", types: true });
  writeFileSync(join(here, "mods", `m${i}.mts`), body);
}
let barrel = "";
for (let i = 0; i < N; i++) barrel += `export * from "./m${i}.mts";\n`;
writeFileSync(join(here, "mods", "index.mts"), barrel);

// 2) the CJS snapshot build entry (functions inlined in the SAME numeric order
//    heavy.mts sorts into, then the same driver registered as the deserialize
//    main function).
let snap =
  `// V8 startup-snapshot build entry for the import-heavy script (GENERATED by\n` +
  `// gen-mods.mjs — do not edit by hand). It inlines the SAME 480 functions that\n` +
  `// mods/*.mts export (TS types stripped, pushed onto FNS in numeric order) plus\n` +
  `// the same reduce driver as heavy.mts. Inlining is required because V8's\n` +
  `// mksnapshot cannot evaluate an ESM module graph at build time.\n` +
  `"use strict";\nconst v8 = require("node:v8");\nconst FNS = [];\n`;
for (let i = 0; i < N; i++) {
  for (let f = 0; f < F; f++) {
    snap += fnSource(i, f, { decl: "function", types: false });
    snap += `FNS.push(m${i}_f${f});\n`;
  }
}
snap +=
  `\nv8.startupSnapshot.setDeserializeMainFunction(() => {\n` +
  `  // Under --snapshot-blob the first user arg is process.argv[1] (no script path).\n` +
  `  const n = Number(process.argv[1] ?? "20");\n` +
  `  let acc = 0;\n` +
  `  for (let i = 0; i < n; i++) acc = (acc + FNS[i % FNS.length](i)) % 1000003;\n` +
  `  console.log(acc);\n});\n`;
writeFileSync(join(here, "heavy-snapshot-entry.cjs"), snap);

console.log(`wrote ${N} modules + barrel + heavy-snapshot-entry.cjs`);
